FROM node:24-alpine

# Set the working directory

WORKDIR /backend

COPY package*.json ./

RUN apk update && apk add --no-cache python3 g++ openjdk11

COPY . .

# Install dependencies

RUN npm install --no-cache-dir -r package.json


EXPOSE 8000

CMD ["node" , "index.js"]